server:
  port: 8081
  servlet:
    context-path: /eShop
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: eShop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.37.45.62:3306/eshop?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: zqxscmr2003
  mail:
    #这个需要根据你开启的服务的邮箱是QQ邮箱,还是网易邮箱区分
    #smtp.163.com为网易邮箱,smtp.qq.com为QQ邮箱
    host: smtp.qq.com
    username: 1197096757@qq.com
    password: xbekmsdvezxcjfig   #授权码
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true
        debug: true
    default-encoding: UTF-8
  data:
    redis:
      host: localhost
      port: 6379
      password: zqxscmr

mybatis:
  mapper-locations: classpath:/mybatis/Mapper/*.xml
  config-location: classpath:/mybatis/config/mybatis-config.xml

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT加解密使用的密钥【私钥】
  secret: zqxlaisiryujiangjunlinrunkai231666
  # JWT的超期限时间(60*60*24*7)---->七天
  expiration: 604800
